name: Build WF
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: run tests on main branch
        run: mvn install

  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code quality
        uses: actions/checkout@v5

      - name: run tests on main branch
        run: mvn test

      - name : checkstyles
        run: mvn checkstyle:checkstyle