name: Build WF
on:
  pull_request:
    branches: [main]
  
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

env:
  ECR_REPOSITORY: vprofile-images

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: run tests on main branch
        run: mvn install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vprofile
          path: target/*.war

      - name: notify if Build fails
        if: failure()
        run: echo "Build Job Failed. Please check the logs for more details."

  Testing:
    name: Testing
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code quality
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name : checkstyles
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: notify if Testing fails
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and checkstyle as the branch is not main."

  Security-Scan:
    name: security scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code quality
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: run security scan on main branch
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          ignore-unfixed: true
          format: json
          exit-code: 0
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: trivy-report.json

      - name: Upload Security Scan Report
        uses: actions/upload-artifact@v7
        with:
          name: trivy-scan-results
          path: trivy-report.json

  Build-Publish-ECR:
    name: BUILD AND PUBLISH TO ECR
    environment: production
    runs-on: ubuntu-latest
    needs: [build, Testing, Security-Scan]
    steps:
      - name: checkout code quality
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Configure AWS login
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run:
          docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: run trivy scan on docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          scan-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          ignore-unfixed: true
          format: json
          exit-code: 0
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: trivy-image-report.json

      - name: Upload Security Scan Report
        uses: actions/upload-artifact@v7
        with:
          name: trivy-scan-results
          path: trivy-image-report.json

      - name: Push Docker image to Amazon ECR
        id: upload-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run:
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


